### ISSUE TITLE
Function '__atomic_fetch_add_4' was not found at compile-time

### ISSUE THREAD

**Issue by mryndak** [robjhyndman/forecast#687]
Calling engine.eval("sword.forecast <- forecast(sword.ts)"); results in an error and it goes as follows:

org.renjin.gcc.runtime.UnsatisfiedLinkException: Function '__atomic_fetch_add_4' was not found at compile-time
at org.renjin.libstdcxx.string_inst._ZN9__gnu_cxxL12__atomic_addEPVii(string-inst.cc:52) ~[libstdcxx-4.7.4-b18.jar:na]
at org.renjin.libstdcxx.string_inst._ZN9__gnu_cxxL21__atomic_add_dispatchEPii(string-inst.cc:95) ~[libstdcxx-4.7.4-b18.jar:na]
at org.renjin.libstdcxx.string_inst.ZNSs4_Rep10_M_refcopyEv(string-inst.cc:260) ~[libstdcxx-4.7.4-b18.jar:na]
at org.renjin.libstdcxx.string_inst.ZNSs4_Rep7_M_grabERKSaIcES2(string-inst.cc:226) ~[libstdcxx-4.7.4-b18.jar:na]
at org.renjin.libstdcxx.string_inst.ZNSsC2ERKSs(string-inst.cc:175) ~[libstdcxx-4.7.4-b18.jar:na]
at org.renjin.cran.forecast.etsTargetFunctionWrapper.etsTargetFunctionInit(etsTargetFunctionWrapper.cpp:68) ~[forecast-8.2-b11.jar:na]
at org.renjin.cran.forecast.forecast.etsTargetFunctionInit(Unknown Source) ~[forecast-8.2-b11.jar:na]
at org.renjin.primitives.Native.redotCall(Native.java:385) ~[renjin-core-0.9.2626.jar:na]
at org.renjin.primitives.R$primitive$$Call.apply(R$primitive$$Call.java:62) ~[renjin-core-0.9.2626.jar:na]
at org.renjin.eval.Context.evaluateCall(Context.java:407) ~[renjin-core-0.9.2626.jar:na]
at org.renjin.eval.Context.evaluate(Context.java:282) ~[renjin-core-0.9.2626.jar:na]
at org.renjin.eval.Context.evaluate(Context.java:264) ~[renjin-core-0.9.2626.jar:na]
at org.renjin.primitives.special.AssignLeftFunction.assignLeft(AssignLeftFunction.java:57) ~[renjin-core-0.9.2626.jar:na]
at org.renjin.primitives.special.AssignLeftFunction.apply(AssignLeftFunction.java:41) ~[renjin-core-0.9.2626.jar:na]
at org.renjin.eval.Context.evaluateCall(Context.java:407) ~[renjin-core-0.9.2626.jar:na]
at org.renjin.eval.Context.evaluate(Context.java:282) ~[renjin-core-0.9.2626.jar:na]
at org.renjin.eval.Context.evaluate(Context.java:264) ~[renjin-core-0.9.2626.jar:na]
at org.renjin.primitives.special.BeginFunction.apply(BeginFunction.java:38) ~[renjin-core-0.9.2626.jar:na]
at org.renjin.eval.Context.evaluateCall(Context.java:407) ~[renjin-core-0.9.2626.jar:na]
at org.renjin.eval.Context.evaluate(Context.java:282) ~[renjin-core-0.9.2626.jar:na]
at org.renjin.eval.Context.evaluate(Context.java:264) ~[renjin-core-0.9.2626.jar:na]
at org.renjin.eval.Context.evaluate(Context.java:198) ~[renjin-core-0.9.2626.jar:na]
at org.renjin.sexp.Closure.doApply(Closure.java:98) ~[renjin-core-0.9.2626.jar:na]
at org.renjin.eval.ClosureDispatcher.apply(ClosureDispatcher.java:80) ~[renjin-core-0.9.2626.jar:na]
at org.renjin.eval.ClosureDispatcher.applyClosure(ClosureDispatcher.java:51) ~[renjin-core-0.9.2626.jar:na]
at org.renjin.sexp.Closure.apply(Closure.java:83) ~[renjin-core-0.9.2626.jar:na]
at org.renjin.eval.Context.evaluateCall(Context.java:407) ~[renjin-core-0.9.2626.jar:na]
at org.renjin.eval.Context.evaluate(Context.java:282) ~[renjin-core-0.9.2626.jar:na]
at org.renjin.eval.Context.evaluate(Context.java:264) ~[renjin-core-0.9.2626.jar:na]
at org.renjin.primitives.special.AssignLeftFunction.assignLeft(AssignLeftFunction.java:57) ~[renjin-core-0.9.2626.jar:na]
at org.renjin.primitives.special.AssignLeftFunction.apply(AssignLeftFunction.java:41) ~[renjin-core-0.9.2626.jar:na]
at org.renjin.eval.Context.evaluateCall(Context.java:407) ~[renjin-core-0.9.2626.jar:na]
at org.renjin.eval.Context.evaluate(Context.java:282) ~[renjin-core-0.9.2626.jar:na]
at org.renjin.eval.Context.evaluate(Context.java:264) ~[renjin-core-0.9.2626.jar:na]
at org.renjin.primitives.special.BeginFunction.apply(BeginFunction.java:38) ~[renjin-core-0.9.2626.jar:na]
at org.renjin.eval.Context.evaluateCall(Context.java:407) ~[renjin-core-0.9.2626.jar:na]
at org.renjin.eval.Context.evaluate(Context.java:282) ~[renjin-core-0.9.2626.jar:na]
at org.renjin.eval.Context.evaluate(Context.java:264) ~[renjin-core-0.9.2626.jar:na]
at org.renjin.eval.Context.evaluate(Context.java:198) ~[renjin-core-0.9.2626.jar:na]
at org.renjin.sexp.Closure.doApply(Closure.java:98) ~[renjin-core-0.9.2626.jar:na]
at org.renjin.eval.ClosureDispatcher.apply(ClosureDispatcher.java:80) ~[renjin-core-0.9.2626.jar:na]
at org.renjin.eval.ClosureDispatcher.applyClosure(ClosureDispatcher.java:51) ~[renjin-core-0.9.2626.jar:na]
at org.renjin.sexp.Closure.apply(Closure.java:83) ~[renjin-core-0.9.2626.jar:na]
at org.renjin.eval.Context.evaluateCall(Context.java:407) ~[renjin-core-0.9.2626.jar:na]
at org.renjin.eval.Context.evaluate(Context.java:282) ~[renjin-core-0.9.2626.jar:na]
at org.renjin.eval.Context.evaluate(Context.java:264) ~[renjin-core-0.9.2626.jar:na]
at org.renjin.primitives.special.AssignLeftFunction.assignLeft(AssignLeftFunction.java:57) ~[renjin-core-0.9.2626.jar:na]
at org.renjin.primitives.special.AssignLeftFunction.apply(AssignLeftFunction.java:41) ~[renjin-core-0.9.2626.jar:na]
at org.renjin.eval.Context.evaluateCall(Context.java:407) ~[renjin-core-0.9.2626.jar:na]
at org.renjin.eval.Context.evaluate(Context.java:282) ~[renjin-core-0.9.2626.jar:na]
at org.renjin.eval.Context.evaluate(Context.java:264) ~[renjin-core-0.9.2626.jar:na]
at org.renjin.primitives.special.BeginFunction.apply(BeginFunction.java:38) ~[renjin-core-0.9.2626.jar:na]
at org.renjin.eval.Context.evaluateCall(Context.java:407) ~[renjin-core-0.9.2626.jar:na]
at org.renjin.eval.Context.evaluate(Context.java:282) ~[renjin-core-0.9.2626.jar:na]
at org.renjin.eval.Context.evaluate(Context.java:264) ~[renjin-core-0.9.2626.jar:na]
at org.renjin.primitives.special.ForFunction.apply(ForFunction.java:89) ~[renjin-core-0.9.2626.jar:na]
at org.renjin.eval.Context.evaluateCall(Context.java:407) ~[renjin-core-0.9.2626.jar:na]
at org.renjin.eval.Context.evaluate(Context.java:282) ~[renjin-core-0.9.2626.jar:na]
at org.renjin.eval.Context.evaluate(Context.java:264) ~[renjin-core-0.9.2626.jar:na]
at org.renjin.primitives.special.BeginFunction.apply(BeginFunction.java:38) ~[renjin-core-0.9.2626.jar:na]
at org.renjin.eval.Context.evaluateCall(Context.java:407) ~[renjin-core-0.9.2626.jar:na]
at org.renjin.eval.Context.evaluate(Context.java:282) ~[renjin-core-0.9.2626.jar:na]
at org.renjin.eval.Context.evaluate(Context.java:264) ~[renjin-core-0.9.2626.jar:na]
at org.renjin.primitives.special.ForFunction.apply(ForFunction.java:89) ~[renjin-core-0.9.2626.jar:na]
at org.renjin.eval.Context.evaluateCall(Context.java:407) ~[renjin-core-0.9.2626.jar:na]
at org.renjin.eval.Context.evaluate(Context.java:282) ~[renjin-core-0.9.2626.jar:na]
at org.renjin.eval.Context.evaluate(Context.java:264) ~[renjin-core-0.9.2626.jar:na]
at org.renjin.primitives.special.BeginFunction.apply(BeginFunction.java:38) ~[renjin-core-0.9.2626.jar:na]
at org.renjin.eval.Context.evaluateCall(Context.java:407) ~[renjin-core-0.9.2626.jar:na]
at org.renjin.eval.Context.evaluate(Context.java:282) ~[renjin-core-0.9.2626.jar:na]
at org.renjin.eval.Context.evaluate(Context.java:264) ~[renjin-core-0.9.2626.jar:na]
at org.renjin.primitives.special.ForFunction.apply(ForFunction.java:89) ~[renjin-core-0.9.2626.jar:na]
at org.renjin.eval.Context.evaluateCall(Context.java:407) ~[renjin-core-0.9.2626.jar:na]
at org.renjin.eval.Context.evaluate(Context.java:282) ~[renjin-core-0.9.2626.jar:na]
at org.renjin.eval.Context.evaluate(Context.java:264) ~[renjin-core-0.9.2626.jar:na]
at org.renjin.primitives.special.BeginFunction.apply(BeginFunction.java:38) ~[renjin-core-0.9.2626.jar:na]
at org.renjin.eval.Context.evaluateCall(Context.java:407) ~[renjin-core-0.9.2626.jar:na]
at org.renjin.eval.Context.evaluate(Context.java:282) ~[renjin-core-0.9.2626.jar:na]
at org.renjin.eval.Context.evaluate(Context.java:264) ~[renjin-core-0.9.2626.jar:na]
at org.renjin.primitives.special.ForFunction.apply(ForFunction.java:89) ~[renjin-core-0.9.2626.jar:na]
at org.renjin.eval.Context.evaluateCall(Context.java:407) ~[renjin-core-0.9.2626.jar:na]
at org.renjin.eval.Context.evaluate(Context.java:282) ~[renjin-core-0.9.2626.jar:na]
at org.renjin.eval.Context.evaluate(Context.java:264) ~[renjin-core-0.9.2626.jar:na]
at org.renjin.primitives.special.BeginFunction.apply(BeginFunction.java:38) ~[renjin-core-0.9.2626.jar:na]
at org.renjin.eval.Context.evaluateCall(Context.java:407) ~[renjin-core-0.9.2626.jar:na]
at org.renjin.eval.Context.evaluate(Context.java:282) ~[renjin-core-0.9.2626.jar:na]
at org.renjin.eval.Context.evaluate(Context.java:264) ~[renjin-core-0.9.2626.jar:na]
at org.renjin.eval.Context.evaluate(Context.java:198) ~[renjin-core-0.9.2626.jar:na]
at org.renjin.sexp.Closure.doApply(Closure.java:98) ~[renjin-core-0.9.2626.jar:na]
at org.renjin.eval.ClosureDispatcher.apply(ClosureDispatcher.java:80) ~[renjin-core-0.9.2626.jar:na]
at org.renjin.eval.ClosureDispatcher.applyClosure(ClosureDispatcher.java:51) ~[renjin-core-0.9.2626.jar:na]
at org.renjin.sexp.Closure.apply(Closure.java:83) ~[renjin-core-0.9.2626.jar:na]
at org.renjin.eval.Context.evaluateCall(Context.java:407) ~[renjin-core-0.9.2626.jar:na]
at org.renjin.eval.Context.evaluate(Context.java:282) ~[renjin-core-0.9.2626.jar:na]
at org.renjin.sexp.Promise.doEval(Promise.java:92) ~[renjin-core-0.9.2626.jar:na]
at org.renjin.sexp.Promise.force(Promise.java:86) ~[renjin-core-0.9.2626.jar:na]
at org.renjin.sexp.Promise.force(Promise.java:80) ~[renjin-core-0.9.2626.jar:na]
at org.renjin.eval.Context.evaluate(Context.java:284) ~[renjin-core-0.9.2626.jar:na]
at org.renjin.eval.Context.evaluate(Context.java:264) ~[renjin-core-0.9.2626.jar:na]
at org.renjin.primitives.S3.UseMethod(S3.java:69) ~[renjin-core-0.9.2626.jar:na]
at org.renjin.primitives.R$primitive$UseMethod.doApply(R$primitive$UseMethod.java:77) ~[renjin-core-0.9.2626.jar:na]
at org.renjin.primitives.R$primitive$UseMethod.apply(R$primitive$UseMethod.java:31) ~[renjin-core-0.9.2626.jar:na]
at org.renjin.eval.Context.evaluateCall(Context.java:407) ~[renjin-core-0.9.2626.jar:na]
at org.renjin.eval.Context.evaluate(Context.java:282) ~[renjin-core-0.9.2626.jar:na]
at org.renjin.eval.Context.evaluate(Context.java:264) ~[renjin-core-0.9.2626.jar:na]
at org.renjin.eval.Context.evaluate(Context.java:198) ~[renjin-core-0.9.2626.jar:na]
at org.renjin.sexp.Closure.doApply(Closure.java:98) ~[renjin-core-0.9.2626.jar:na]
at org.renjin.eval.ClosureDispatcher.apply(ClosureDispatcher.java:80) ~[renjin-core-0.9.2626.jar:na]
at org.renjin.eval.ClosureDispatcher.applyClosure(ClosureDispatcher.java:51) ~[renjin-core-0.9.2626.jar:na]
at org.renjin.sexp.Closure.apply(Closure.java:83) ~[renjin-core-0.9.2626.jar:na]
at org.renjin.eval.Context.evaluateCall(Context.java:407) ~[renjin-core-0.9.2626.jar:na]
at org.renjin.eval.Context.evaluate(Context.java:282) ~[renjin-core-0.9.2626.jar:na]
at org.renjin.eval.Context.evaluate(Context.java:264) ~[renjin-core-0.9.2626.jar:na]
at org.renjin.primitives.special.AssignLeftFunction.assignLeft(AssignLeftFunction.java:57) ~[renjin-core-0.9.2626.jar:na]
at org.renjin.primitives.special.AssignLeftFunction.apply(AssignLeftFunction.java:41) ~[renjin-core-0.9.2626.jar:na]
at org.renjin.eval.Context.evaluateCall(Context.java:407) ~[renjin-core-0.9.2626.jar:na]
at org.renjin.eval.Context.evaluate(Context.java:282) ~[renjin-core-0.9.2626.jar:na]
at org.renjin.eval.Context.evaluate(Context.java:264) ~[renjin-core-0.9.2626.jar:na]
at org.renjin.primitives.special.IfFunction.apply(IfFunction.java:40) ~[renjin-core-0.9.2626.jar:na]
at org.renjin.eval.Context.evaluateCall(Context.java:407) ~[renjin-core-0.9.2626.jar:na]
at org.renjin.eval.Context.evaluate(Context.java:282) ~[renjin-core-0.9.2626.jar:na]
at org.renjin.eval.Context.evaluate(Context.java:264) ~[renjin-core-0.9.2626.jar:na]
at org.renjin.primitives.special.BeginFunction.apply(BeginFunction.java:38) ~[renjin-core-0.9.2626.jar:na]
at org.renjin.eval.Context.evaluateCall(Context.java:407) ~[renjin-core-0.9.2626.jar:na]
at org.renjin.eval.Context.evaluate(Context.java:282) ~[renjin-core-0.9.2626.jar:na]
at org.renjin.eval.Context.evaluate(Context.java:264) ~[renjin-core-0.9.2626.jar:na]
at org.renjin.primitives.special.IfFunction.apply(IfFunction.java:40) ~[renjin-core-0.9.2626.jar:na]
at org.renjin.eval.Context.evaluateCall(Context.java:407) ~[renjin-core-0.9.2626.jar:na]
at org.renjin.eval.Context.evaluate(Context.java:282) ~[renjin-core-0.9.2626.jar:na]
at org.renjin.eval.Context.evaluate(Context.java:264) ~[renjin-core-0.9.2626.jar:na]
at org.renjin.primitives.special.BeginFunction.apply(BeginFunction.java:38) ~[renjin-core-0.9.2626.jar:na]
at org.renjin.eval.Context.evaluateCall(Context.java:407) ~[renjin-core-0.9.2626.jar:na]
at org.renjin.eval.Context.evaluate(Context.java:282) ~[renjin-core-0.9.2626.jar:na]
at org.renjin.eval.Context.evaluate(Context.java:264) ~[renjin-core-0.9.2626.jar:na]
at org.renjin.eval.Calls.applyClosure(Calls.java:47) ~[renjin-core-0.9.2626.jar:na]
at org.renjin.primitives.S3$GenericMethod.doApply(S3.java:1459) ~[renjin-core-0.9.2626.jar:na]
at org.renjin.primitives.S3$GenericMethod.apply(S3.java:1408) ~[renjin-core-0.9.2626.jar:na]
at org.renjin.primitives.S3.UseMethod(S3.java:84) ~[renjin-core-0.9.2626.jar:na]
at org.renjin.primitives.S3.UseMethod(S3.java:72) ~[renjin-core-0.9.2626.jar:na]
at org.renjin.primitives.R$primitive$UseMethod.doApply(R$primitive$UseMethod.java:77) ~[renjin-core-0.9.2626.jar:na]
at org.renjin.primitives.R$primitive$UseMethod.apply(R$primitive$UseMethod.java:31) ~[renjin-core-0.9.2626.jar:na]
at org.renjin.eval.Context.evaluateCall(Context.java:407) ~[renjin-core-0.9.2626.jar:na]
at org.renjin.eval.Context.evaluate(Context.java:282) ~[renjin-core-0.9.2626.jar:na]
at org.renjin.eval.Context.evaluate(Context.java:264) ~[renjin-core-0.9.2626.jar:na]
at org.renjin.eval.Context.evaluate(Context.java:198) ~[renjin-core-0.9.2626.jar:na]
at org.renjin.sexp.Closure.doApply(Closure.java:98) ~[renjin-core-0.9.2626.jar:na]
at org.renjin.eval.ClosureDispatcher.apply(ClosureDispatcher.java:80) ~[renjin-core-0.9.2626.jar:na]
at org.renjin.eval.ClosureDispatcher.applyClosure(ClosureDispatcher.java:51) ~[renjin-core-0.9.2626.jar:na]
at org.renjin.sexp.Closure.apply(Closure.java:83) ~[renjin-core-0.9.2626.jar:na]
at org.renjin.eval.Context.evaluateCall(Context.java:407) ~[renjin-core-0.9.2626.jar:na]
at org.renjin.eval.Context.evaluate(Context.java:282) ~[renjin-core-0.9.2626.jar:na]
at org.renjin.eval.Context.evaluate(Context.java:264) ~[renjin-core-0.9.2626.jar:na]
at org.renjin.primitives.special.AssignLeftFunction.assignLeft(AssignLeftFunction.java:57) ~[renjin-core-0.9.2626.jar:na]
at org.renjin.primitives.special.AssignLeftFunction.apply(AssignLeftFunction.java:41) ~[renjin-core-0.9.2626.jar:na]
at org.renjin.eval.Context.evaluateCall(Context.java:407) ~[renjin-core-0.9.2626.jar:na]
at org.renjin.eval.Context.evaluate(Context.java:282) ~[renjin-core-0.9.2626.jar:na]
at org.renjin.eval.Context.evaluate(Context.java:264) ~[renjin-core-0.9.2626.jar:na]
at org.renjin.eval.Context.evaluateExpressionVector(Context.java:390) ~[renjin-core-0.9.2626.jar:na]
at org.renjin.eval.Context.evaluate(Context.java:280) ~[renjin-core-0.9.2626.jar:na]
at org.renjin.eval.Context.evaluate(Context.java:264) ~[renjin-core-0.9.2626.jar:na]
at org.renjin.script.RenjinScriptEngine.eval(RenjinScriptEngine.java:168) ~[renjin-script-engine-0.9.2626.jar:na]
at org.renjin.script.RenjinScriptEngine.eval(RenjinScriptEngine.java:127) ~[renjin-script-engine-0.9.2626.jar:na]
at pl.mryndak.bloodmonitor.service.forecasting.RTest.testMethod(RTest.java:38) ~[classes/:na]
at pl.mryndak.bloodmonitor.web.rest.FirstMLController.testMethod(FirstMLController.java:16) ~[classes/:na]
at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[na:1.8.0_161]
at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[na:1.8.0_161]
at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[na:1.8.0_161]
at java.lang.reflect.Method.invoke(Method.java:498) ~[na:1.8.0_161]
at org.springframework.web.method.support.InvocableHandlerMethod.doInvoke(InvocableHandlerMethod.java:205) ~[spring-web-4.3.14.RELEASE.jar:4.3.14.RELEASE]
at org.springframework.web.method.support.InvocableHandlerMethod.invokeForRequest(InvocableHandlerMethod.java:133) ~[spring-web-4.3.14.RELEASE.jar:4.3.14.RELEASE]
at org.springframework.web.servlet.mvc.method.annotation.ServletInvocableHandlerMethod.invokeAndHandle(ServletInvocableHandlerMethod.java:97) ~[spring-webmvc-4.3.14.RELEASE.jar:4.3.14.RELEASE]
at org.springframework.web.servlet.mvc.method.annotation.RequestMappingHandlerAdapter.invokeHandlerMethod(RequestMappingHandlerAdapter.java:827) ~[spring-webmvc-4.3.14.RELEASE.jar:4.3.14.RELEASE]
at org.springframework.web.servlet.mvc.method.annotation.RequestMappingHandlerAdapter.handleInternal(RequestMappingHandlerAdapter.java:738) ~[spring-webmvc-4.3.14.RELEASE.jar:4.3.14.RELEASE]
at org.springframework.web.servlet.mvc.method.AbstractHandlerMethodAdapter.handle(AbstractHandlerMethodAdapter.java:85) ~[spring-webmvc-4.3.14.RELEASE.jar:4.3.14.RELEASE]
at org.springframework.web.servlet.DispatcherServlet.doDispatch(DispatcherServlet.java:967) ~[spring-webmvc-4.3.14.RELEASE.jar:4.3.14.RELEASE]
at org.springframework.web.servlet.DispatcherServlet.doService(DispatcherServlet.java:901) ~[spring-webmvc-4.3.14.RELEASE.jar:4.3.14.RELEASE]
at org.springframework.web.servlet.FrameworkServlet.processRequest(FrameworkServlet.java:970) ~[spring-webmvc-4.3.14.RELEASE.jar:4.3.14.RELEASE]
at org.springframework.web.servlet.FrameworkServlet.doGet(FrameworkServlet.java:861) ~[spring-webmvc-4.3.14.RELEASE.jar:4.3.14.RELEASE]
at javax.servlet.http.HttpServlet.service(HttpServlet.java:635) ~[tomcat-embed-core-8.5.27.jar:8.5.27]
at org.springframework.web.servlet.FrameworkServlet.service(FrameworkServlet.java:846) ~[spring-webmvc-4.3.14.RELEASE.jar:4.3.14.RELEASE]
at javax.servlet.http.HttpServlet.service(HttpServlet.java:742) ~[tomcat-embed-core-8.5.27.jar:8.5.27]
at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:231) ~[tomcat-embed-core-8.5.27.jar:8.5.27]
at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166) ~[tomcat-embed-core-8.5.27.jar:8.5.27]
at org.apache.tomcat.websocket.server.WsFilter.doFilter(WsFilter.java:52) ~[tomcat-embed-websocket-8.5.27.jar:8.5.27]
at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193) ~[tomcat-embed-core-8.5.27.jar:8.5.27]
at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166) ~[tomcat-embed-core-8.5.27.jar:8.5.27]
at org.springframework.boot.web.filter.ApplicationContextHeaderFilter.doFilterInternal(ApplicationContextHeaderFilter.java:55) ~[spring-boot-1.5.10.RELEASE.jar:1.5.10.RELEASE]
at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:107) ~[spring-web-4.3.14.RELEASE.jar:4.3.14.RELEASE]
at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193) ~[tomcat-embed-core-8.5.27.jar:8.5.27]
at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166) ~[tomcat-embed-core-8.5.27.jar:8.5.27]
at org.springframework.boot.actuate.trace.WebRequestTraceFilter.doFilterInternal(WebRequestTraceFilter.java:110) ~[spring-boot-actuator-1.5.10.RELEASE.jar:1.5.10.RELEASE]
at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:107) ~[spring-web-4.3.14.RELEASE.jar:4.3.14.RELEASE]
at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193) ~[tomcat-embed-core-8.5.27.jar:8.5.27]
at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166) ~[tomcat-embed-core-8.5.27.jar:8.5.27]
at org.springframework.security.web.FilterChainProxy.doFilterInternal(FilterChainProxy.java:208) ~[spring-security-web-4.2.4.RELEASE.jar:4.2.4.RELEASE]
at org.springframework.security.web.FilterChainProxy.doFilter(FilterChainProxy.java:177) ~[spring-security-web-4.2.4.RELEASE.jar:4.2.4.RELEASE]
at org.springframework.web.filter.DelegatingFilterProxy.invokeDelegate(DelegatingFilterProxy.java:347) ~[spring-web-4.3.14.RELEASE.jar:4.3.14.RELEASE]
at org.springframework.web.filter.DelegatingFilterProxy.doFilter(DelegatingFilterProxy.java:263) ~[spring-web-4.3.14.RELEASE.jar:4.3.14.RELEASE]
at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193) ~[tomcat-embed-core-8.5.27.jar:8.5.27]
at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166) ~[tomcat-embed-core-8.5.27.jar:8.5.27]
at org.springframework.web.filter.RequestContextFilter.doFilterInternal(RequestContextFilter.java:99) ~[spring-web-4.3.14.RELEASE.jar:4.3.14.RELEASE]
at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:107) ~[spring-web-4.3.14.RELEASE.jar:4.3.14.RELEASE]
at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193) ~[tomcat-embed-core-8.5.27.jar:8.5.27]
at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166) ~[tomcat-embed-core-8.5.27.jar:8.5.27]
at org.springframework.web.filter.HttpPutFormContentFilter.doFilterInternal(HttpPutFormContentFilter.java:108) ~[spring-web-4.3.14.RELEASE.jar:4.3.14.RELEASE]
at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:107) ~[spring-web-4.3.14.RELEASE.jar:4.3.14.RELEASE]
at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193) ~[tomcat-embed-core-8.5.27.jar:8.5.27]
at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166) ~[tomcat-embed-core-8.5.27.jar:8.5.27]
at org.springframework.web.filter.HiddenHttpMethodFilter.doFilterInternal(HiddenHttpMethodFilter.java:81) ~[spring-web-4.3.14.RELEASE.jar:4.3.14.RELEASE]
at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:107) ~[spring-web-4.3.14.RELEASE.jar:4.3.14.RELEASE]
at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193) ~[tomcat-embed-core-8.5.27.jar:8.5.27]
at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166) ~[tomcat-embed-core-8.5.27.jar:8.5.27]
at org.springframework.web.filter.CharacterEncodingFilter.doFilterInternal(CharacterEncodingFilter.java:197) ~[spring-web-4.3.14.RELEASE.jar:4.3.14.RELEASE]
at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:107) ~[spring-web-4.3.14.RELEASE.jar:4.3.14.RELEASE]
at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193) ~[tomcat-embed-core-8.5.27.jar:8.5.27]
at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166) ~[tomcat-embed-core-8.5.27.jar:8.5.27]
at org.springframework.boot.actuate.autoconfigure.MetricsFilter.doFilterInternal(MetricsFilter.java:106) ~[spring-boot-actuator-1.5.10.RELEASE.jar:1.5.10.RELEASE]
at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:107) ~[spring-web-4.3.14.RELEASE.jar:4.3.14.RELEASE]
at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193) ~[tomcat-embed-core-8.5.27.jar:8.5.27]
at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166) ~[tomcat-embed-core-8.5.27.jar:8.5.27]
at org.apache.catalina.core.StandardWrapperValve.invoke(StandardWrapperValve.java:199) ~[tomcat-embed-core-8.5.27.jar:8.5.27]
at org.apache.catalina.core.StandardContextValve.invoke(StandardContextValve.java:96) [tomcat-embed-core-8.5.27.jar:8.5.27]
at org.apache.catalina.authenticator.AuthenticatorBase.invoke(AuthenticatorBase.java:504) [tomcat-embed-core-8.5.27.jar:8.5.27]
at org.apache.catalina.core.StandardHostValve.invoke(StandardHostValve.java:140) [tomcat-embed-core-8.5.27.jar:8.5.27]
at org.apache.catalina.valves.ErrorReportValve.invoke(ErrorReportValve.java:81) [tomcat-embed-core-8.5.27.jar:8.5.27]
at org.apache.catalina.core.StandardEngineValve.invoke(StandardEngineValve.java:87) [tomcat-embed-core-8.5.27.jar:8.5.27]
at org.apache.catalina.connector.CoyoteAdapter.service(CoyoteAdapter.java:342) [tomcat-embed-core-8.5.27.jar:8.5.27]
at org.apache.coyote.http11.Http11Processor.service(Http11Processor.java:803) [tomcat-embed-core-8.5.27.jar:8.5.27]
at org.apache.coyote.AbstractProcessorLight.process(AbstractProcessorLight.java:66) [tomcat-embed-core-8.5.27.jar:8.5.27]
at org.apache.coyote.AbstractProtocol$ConnectionHandler.process(AbstractProtocol.java:790) [tomcat-embed-core-8.5.27.jar:8.5.27]
at org.apache.tomcat.util.net.NioEndpoint$SocketProcessor.doRun(NioEndpoint.java:1459) [tomcat-embed-core-8.5.27.jar:8.5.27]
at org.apache.tomcat.util.net.SocketProcessorBase.run(SocketProcessorBase.java:49) [tomcat-embed-core-8.5.27.jar:8.5.27]
at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149) [na:1.8.0_161]
at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624) [na:1.8.0_161]
at org.apache.tomcat.util.threads.TaskThread$WrappingRunnable.run(TaskThread.java:61) [tomcat-embed-core-8.5.27.jar:8.5.27]
at java.lang.Thread.run(Thread.java:748) [na:1.8.0_161]

**Comment by robjhyndman** [comment]
This looks like a renjin problem. In any case, I do not attempt to make forecast compatible with renjin.
